const languageScript = {
    currentLanguage: {}, // the currently used language object
    //switch the currentLanguage Object
    changeLanguage() {
        if (languageScript.currentLanguage === languageScript.englishLanguage) languageScript.currentLanguage = languageScript.germanLanguage;
        else languageScript.currentLanguage = languageScript.englishLanguage;
        this.reloadLanguage();
    },
    //reload all language elements and set the data from the currentLanguage object
    reloadLanguage(){
        let languageElements = document.getElementsByClassName("languageText");
        [...languageElements].forEach(element => {
            const langId = [...element.classList].find(e => {
                return e.includes("langId-");
            }).split("-")[1];
            element.innerHTML = languageScript.currentLanguage[langId];
        });
    },
    englishLanguage: {
        home: "HOME",
        downloads: "DOWNLOADS",
        installation: "INSTALLATION",
        features: "PLANNED FEATURES",
        faq: "FAQ",
        legal_notice: "Legal Notice",
        contact: "Contact Us",
        privacy_policy: "Privacy Policy",
        contact_data: "Your Contact Data",
        contact_topic: "Topic:*",
        contact_select_placeholder: "-- Please Select --",
        contact_select_errorReport: "Report an Error",
        contact_select_newFeature: "New Feature Idea",
        contact_message: "Your Message:*",
        contact_cancel: "Cancel",
        contact_submit: "Submit",
        issues_caption: "Planned Features",
        required_fields: "* - Required Fields",
        about_header: "About TvSeriesCalendar",
        about_text: "TvSeriesCalendar is an open-source software for all series fans. No matter the show, never miss the start of a whole series or a new season.<br><br>Here you gonna find all the information about the project.<br>If you wish to download the project, or want to see which versions are currently available, click on Downloads.<br>Need help with installing the software, click on Installation.<br>Do you have specific questions regarding the project? Take a look at the F.A.Q. or ask us directly via the contact formular.",
        feature_series_libary_header: "Series libary of the user",
        feature_series_libary_subheader1: "General view of your series libary",
        feature_series_libary_description1: "You can find all Series, which you added to your series libary in the tab 'Series'.<br>Every series contains the following properties:<blockquote>- The cover<br>- The name<br>- The release date of the next season<br>- Your status of the series, which is marked by an outline around the element(e.g. a red outline means the series is completed or cancelled and you already watched every aired episode).</blockquote>You can click on every series to get to the detailed view.",
        feature_series_libary_subheader2: "The detailed view of a series in your libary",
        feature_series_libary_description2: " In the detailed view more information about the series are shown. Here you can also make changes to the series. As a port of it you can edit your watched season, which results to an adaption of the release date to the next season. The changes can be confirmed or cancelled at the bottom of the view. You can close the detailed view by confirming, cancelling or clicking on the X in the top right corner. Here you also have the option to delete a series from your libary, by clicking on the button in the top left corner.",
        feature_search_header: "Search for a series",
        feature_search_subheader1: "General view of your search",
        feature_search_description1: "This view makes it possible to search for any series by entering a titel in the searchbar. All results will be listed up to a maximum of 20 matches. The series are displayed by:<blockquote>- The cover<br>- The name<br>- The release date of the first season<br>- The current status marked by an outline around the element, just like in the series libary</blockquote>You are directed to the detailed view by clicking on a series.",
        feature_search_subheader2: "The detailed view of a searched series",
        feature_search_description2: "After you clicked on a search result, more details of the series are shown. Fit the already watched seasons to your pleasure, before adding the series to your libary by clicking the button in the bottom of the view. The detailed view will be left automatically by adding the series to your libary. You also can manually leave by pressing the X in the top right corner.",
        feature_configuration_header: "Settings of the program",
        feature_configuration_description: "There is currently only one setting for the program. By enabling this setting, the program will automatically update your series.",
        feature_update_series_header: "Automatical update of your series libary",
        feature_update_series_description: "If the setting for the automatical updates is enabled, the program checks for any updated information about your series, whenever you log in to your windows-user. If relevant information are found, a small dialog will open to inform you about the changes. In response you can either open the program or dismiss the notification.",
        feature_information_header: "Additional information",
        feature_information_description: "In this category you can find further information about the program. <br>Amongst other things the used libaries and a link to The Movie Database, which is used to collect all the information about the series.",
        feature_update_program_header: "Automatical updating of the program",
        feature_update_program_description: "As long as an internet connection exists, the program will automatically check for a new available version. <br>If a new version is found, it will be downloaded and installed. All of your series stay in your libary after any update!",
        legal_notice_MainInfo: "Herewith, we assume no responsibility for all activities on the website. Your personal information is disclosed to third parties and processed by their privacy policies.",
        legal_notice_additionalInfo: "Additional legal informations can be found on the <a href='#NavDatenschutz'>Privacy Policy</a> page.",
        privacy_policy_personalData_header: "Collection of personal data",
        privacy_policy_personalData_info1: "We do not collect any personal data.",
        privacy_policy_personalData_info2: "Use of personal data",
        privacy_policy_personalData_info3: "We do not use any personal data. We only forward the data on the contact form to Formspree.io, who process it in accordance with their data protection declarations",
        privacy_policy_cookies_header: "Use of cookies",
        privacy_policy_cookies_info: "The function of cookies is not implemented on this website",
        privacy_policy_termsOfUse_header: "Terms of Use",
        privacy_policy_termsOfUse_info: "By using the software you accept the following terms of use. The software is subject to the <a href='https://raw.githubusercontent.com/Death-Truction/TvSeriesCalendar/master/LICENSE' target='_blank'>GNU GPL 3</a> license and may only be used for private and non-commercial purposes. Failure to do so may result in fines, including the transfer of all winnings by the software to the author. ",
        privacy_policy_thirdParty_header: "Third party",
        privacy_policy_thirdParty_info: "We use third-party software, including Images from GitHub and iFrames from Google. We also offer a Formspree contact form. By using this software you accept its privacy policy. For more information, you can read their privacy policy and terms of use.",
        faq_question_1: "Why is the wrong picture displayed for a series?",
        faq_answer_1: "All data on the series is retrieved from the series database The Movie Databse (TMDb). If there is incorrect data, it is due to the incorrect information from the database.",
        faq_question_2: "Why is the release date of a series / season shown in the past?",
        faq_answer_2: "The series / current season has already been released, but the release date is still displayed.",
        faq_question_3: "The release date is in the past, why is the series still not to be found on Netflix or similar?",
        faq_answer_3: "The release date indicates when the series will be released in its original setting. This series may not yet be available in your country or at your streaming provider.",
        faq_question_4: "Can I add an unlimited number of series to my library?",
        faq_answer_4: "Since the program is stored locally, you can add as many series as your device allows.",
        faq_question_5: "Is the program really free?",
        faq_answer_5: "Yes, the software is completely free for private use.",
        faq_question_6: "How can I support TvSeriesCalendar?",
        faq_answer_6: "At the moment this is not yet possible, PayPal may be set up for this.",        
        installation_title: "Step by step instructions for installing the software",
        installation_navigation: "1. You can download an executable version <a> directly (recommended) </a> <br> 2. You can download the project and <a> compile it yourself with Visual Studio </a>",
        installation_preCompiled: "<h3> Download the executable file: </h3> 1. Go to the <a href='#NavDownloads'> Downloads page </a> <br> 2. In the top column you will find the latest version of the application <br> 3. If you have a 64-bit system, download the file that ends in x64.zip <br>&nbsp;&nbsp;&nbsp;&nbsp;If you have a 32-bit system, download the file that ends in x86.zip <br> 4. Unzip the downloaded .zip file <br> 5. Start the file TvSeriesCalendar.exe <br> 6. Have fun with the application! <br>",
        installation_selfCompiled: "<h3> Download the source code: </h3> 1. Go to the <a href='https://github.com/Death-Truction/TvSeriesCalendar' target='_blank'> page of the Github project </a> <br> 2. Click on the green button with the text \"Code\" <br> 3. Either clone the project with git or download the project as a .zip file and unzip it <br> 4. Go to the SourceCode subfolder and open the TvSeriesCalender.sln file with Visual Studio <br> 5. Compile the project and start the compiled .exe file <br> 6. Have fun with the application! <br>",
    },
    germanLanguage: {
        home: "STARTSEITE",
        downloads: "DOWNLOADS",
        installation: "INSTALLATION",
        features: "GEPLANTE FEATURES",
        faq: "FAQ",
        legal_notice: "Impressum",
        contact: "Kontakt",
        privacy_policy: "Datenschutz",
        contact_data: "Ihre Kontaktdaten",
        contact_topic: "Thema:*",
        contact_select_placeholder: "-- Bitte Auswählen --",
        contact_select_errorReport: "Fehlermeldung",
        contact_select_newFeature: "Verbesserungsvorschlag",
        contact_message: "Ihre Nachricht:*",
        contact_cancel: "Abbrechen",
        contact_submit: "Abschicken",
        issues_caption: "Geplante Features",
        required_fields: "* - Pflichtfelder",
        about_header: "Über das Projekt TvSeriesCalendar",
        about_text: "TvSeriesCalendar ist eine Open-Source Software für alle Serienfans. Egal um welche Show es geht, verpassen Sie nie wieder den Start einer ganzen Serie oder einer weiteren Staffel.<br><br>Hier finden Sie alle Informationen zu dem Projekt.<br>Wenn Sie das Projekt herunterladen, oder sehen möchten welche Versionen aktuell verfügbar sind, klicken Sie auf Downloads.<br>Brauchen Sie Hilfe beim Installieren der Software, dann klicken Sie auf Installation.<br>Haben Sie spezifische Fragen? Durchsuchen Sie unser F.A.Q. und falls es ungeklärte Fragen gibt können Sie gerne Kontakt zu uns aufnehmen.",
        feature_series_libary_header: "Serienbibliothek des Nutzers",
        feature_series_libary_subheader1: "Allgemeine Ansicht Ihrer Serienbibliothek",
        feature_series_libary_description1: "Im Tab 'Series' Finden Sie alle Serien, die sie ihrer Serienbibliothek hinzugefügt haben.<br>Jeder Serie wird dargestellt durch:<blockquote>- Das Cover<br>- Den Namen<br>- Das Veröffentlichungsdatum der nächsten Staffel<br>- Ihren aktuellen Status zu der Serie, welcher durch die Umrandung des Serienelementes gekennzeichnet wird (z.B. eine rote Umrandung, wenn die Serie abgeschlossen ist oder abgebrochen wurde und Sie bereits alle ausgestrahlten Serien geschaut haben).</blockquote>Sie können jede dieser Serien anklicken, wodurch Sie zur detaillierten Ansicht der angeklickten Serie kommen.",
        feature_series_libary_subheader2: "Die detaillierte Ansicht einer Serie in der eigenen Bibliothek",
        feature_series_libary_description2: " In der detaillierten Ansicht werden weitere Informationen zu der Serie dargestellt. Zusätzlich zu den angezeigten Informationen können Sie hier Änderungen an der Serie vornehmen. Dazu gehört die Anpassung der von Ihnen geschauten Staffeln, wobei sich dadurch auch direkt das Veröffentlichungsdatum der nächsten Staffel anpasst. Die Veränderungen können Sie mit den Knöpfen am unteren Ende der Ansicht entweder speichern oder verwerfen. Schließen können Sie die ansicht, indem sie Ihre Änderungen speichern, verwerfen oder auf das X in der oberen rechten Ecke klicken. Außerdem bietet die Ansicht Ihnen die Möglichkeit die Serie aus Ihrer Bibliothek zu entfernen, indem Sie auf den Knopf in der oberen linken Ecke klicken",
        feature_search_header: "Suche nach Serien",
        feature_search_subheader1: "Allgemeine Ansicht Ihrer Suche",
        feature_search_description1: "Diese Ansicht ermöglicht es Ihnen, durch die Eingabe eines Titels in die Suchleiste, nach beliebigen Serien zu Suchen. Alle Ergebnisse der Suche werden dann aufgelistet, wobei pro Seite maximal 20 Treffer dargestellt werden. Auch hier werden die einzelnen Serien dargestellt durch:<blockquote>- Das Cover<br>- Den Namen<br>- Das Veröffentlichungsdatum der ersten Staffel<br>- Den aktuellen Status, welcher durch die Umrandung des Serienelementes gekennzeichnet wird (wie in Ihrer Serienbibliothek)</blockquote>Durch das anklicken einer Serie kommen Sie zur detaillierten Ansicht der Serie.",
        feature_search_subheader2: "Die detaillierte Ansicht einer Serie Ihrer Suche",
        feature_search_description2: "Nach dem Sie eine Serie Ihres Suchresultates angeklickt haben, werden Ihnen weitere Details zu der Serie angezeigt. Passen Sie hier die Anzahl der bereits geschauten Staffeln an, bevor sie die Serie über den Knopf am unteren Ende der Ansicht zu Ihrer Serienbibliothek hinzufügen. Die detaillierte Ansicht wird automatisch beim hinzufügen der Serie zu Ihrer Bibliothek, geschlossen. Sie können die Ansicht aber auch durch einen manuellen Klick auf das X in der oberen rechten Ecke schließen.",
        feature_configuration_header: "Einstellungen des Programms",
        feature_configuration_description: "Derzeit gibt es nur eine Einstellung für das Programm. Durch die Auswahl dieser Einstellung, wird das automatische Updaten Ihrer Serien aktiviert.",
        feature_update_series_header: "Automatische Updates Ihrer Serienbibliothek",
        feature_update_series_description: "Wenn Sie die Einstellung für die automatischen Updates aktiviert haben, werden Ihre Serien automatisch nach jeder Anmeldung Ihres Windows-Benutzers aktualisiert. Sollte es neue relevante Informationen zu Ihren Serien geben, wird ein kleines Fenster mit den neuen Informationen angezeigt. Daraufhin können Sie entweder das Programm öffnen oder die Mitteilung schließen.",
        feature_information_header: "Weitere Informationen",
        feature_information_description: "Hier finden Sie weitere Informationen zu dem Programm. <br>Unter anderem die benutzten Bibliotheken oder auch den Link zu The Movie Database, der genutzten Datenbank für die Serien.",
        feature_update_program_header: "Automatisches Updaten des Programms",
        feature_update_program_description: "Sofern eine Internetverbindung besteht wird beim Starten des Programms automatisch überprüft, ob eine neue Version verfügbar ist. <br>Gibt es eine neue Version, so wird diese heruntergeladen und installiert. Dabei bleiben sämtliche Serien in Ihrer Serienbiliothek erhalten!",
        legal_notice_MainInfo: "Hiermit übernehmen wir keine Verantwortung über sämtliche Aktivitäten auf der Webseite. Ihre Daten werden an Dritte weitergegeben und nach deren Datenschutzerklärungen verarbeitet.",
        legal_notice_additionalInfo: "Weitere rechtliche Angaben finden Sie auf der <a href='#NavDatenschutz'>Datenschutz</a> Seite.",
        privacy_policy_personalData_header: "Erhebung personenbezogener Daten",
        privacy_policy_personalData_info1: "Es werden keine personenbezogene Daten von uns erhoben.",
        privacy_policy_personalData_info2: "Verwendung personenbezogener Daten",
        privacy_policy_personalData_info3: "Wir verwenden keinerlei personenbezogene Daten. Wir geben ausschließlich die Daten des Kontaktformulars an Formspree.io weiter, die diese nach ihren Datenschutzerklärungen verarbeiten",
        privacy_policy_cookies_header: "Verwendung von Cookies",
        privacy_policy_cookies_info: "Die Funktion von Cookies sind auf dieser Webseite nicht implementiert",
        privacy_policy_termsOfUse_header: "Nutzungsbedingungen",
        privacy_policy_termsOfUse_info: "Durch das Nutzen der Software akzeptieren Sie die folgenden Nutzungsbedingungen. Die Software untersteht der <a href='https://raw.githubusercontent.com/Death-Truction/TvSeriesCalendar/master/LICENSE'  target='_blank'>GNU GPL 3</a> Lizenz und darf ausschließlich für private und nicht kommerzielle Zwecke verwendet werden. Bei Missachtung drohen Geldstrafen einschließlich Abgabe sämtlicher Gewinne durch die Software an den Urheber. ",
        privacy_policy_thirdParty_header: "Drittanbieter",
        privacy_policy_thirdParty_info: "Wir verwenden Software von Drittanbietern, darunter werden Bilder von GitHub und iFrames von Google geladen. Desweiteren bieten wir ein Kontaktformular von Formspree an. Bei Nutzung dieser Software akzeptieren Sie deren Datenschutzbestimmungen. Für mehr Informationen können Sie deren Datenschutzbestimmungen und Nutzungsbedingungen lesen.",
        faq_question_1: "Warum wird bei einer Serie ein falsches Bild angezeigt?",
        faq_answer_1: "Sämtliche Daten zu den Serien, werden von der Seriendatenbank The Movie Databse (TMDb) abgerufen. Sollte es falsche Daten geben, dann liegt es an den fehlerhaften Informationen von der Datenbank.",
        faq_question_2: "Warum liegt das angezeigte Veröffentlichungsdatum einer Serie / Staffel in der Vergangenheit?",
        faq_answer_2: "Die Serie / die aktuelle Staffel ist schon erschienen, es wird trotzdem das Veröffentlichungsdatum angezeigt.",
        faq_question_3: "Das Veröffentlichungsdatum liegt in der Vergangenheit, warum ist die Serie trotzdem nicht auf Netflix o.ä. zu finden?",
        faq_answer_3: "Das Veröffentlichungsdatum zeigt an, wann die Serie in Originalvertonung veröffentlicht wird. Es kann sein, dass diese Serie noch nicht in deinem Land, oder bei deinem Streaminganbieter verfügbar ist.",
        faq_question_4: "Kann ich unbegrenzt viele Serien meiner Bibliothek hinzufügen?",
        faq_answer_4: "Da das Programm bei Ihnen lokal gespeichert ist, können Sie so viele Serien hinzufügen, wie ihr Gerät es erlaubt.",
        faq_question_5: "Ist das Programm wirklich kostenlos?",
        faq_answer_5: "Ja, die Software ist für den Privatgebrauch komplett frei benutzbar.",
        faq_question_6: "Wie kann ich TvSeriesCalendar unterstützen?",
        faq_answer_6: "Im Moment ist das noch nicht möglich, es wird eventuell PayPal dafür eingerichtet.",
        installation_title: "Schritt für Schritt Anleitung zum Installieren der Software",
        installation_navigation: "1. Sie können sich eine ausführbare Version <a>direkt herunterladen(emfohlen)</a><br>2. Sie können sich das Projekt herunterladen und dieses <a>selbständig mit Visual Studio kompilieren</a>",
        installation_preCompiled: "<h3>Download der ausführbaren Datei:</h3>1. Gehen Sie auf die <a href='#NavDownloads'>Downloads Seite</a><br>2. In der obersten Spalte finden Sie die neuste Version der Applikation<br>3. Wenn Sie ein 64-Bit System haben, dann laden Sie die Datei herunter, die auf x64.zip endet<br>&nbsp;&nbsp;&nbsp;&nbsp;Wenn Sie ein 32-Bit System haben, dann laden Sie die Datei herunter, die auf x86.zip endet<br>4. Entpacken Sie die heruntergeladene .zip-Datei<br>5. Starten Sie die Datei TvSeriesCalendar.exe<br>6. Viel spaß mit der Applikation!<br>",
        installation_selfCompiled: "<h3>Download des Quellcodes:</h3>1. Gehen Sie auf die <a href='https://github.com/Death-Truction/TvSeriesCalendar' target='_blank'>Seite des Githubprojektes</a><br>2. Klicken Sie auf den Grünen Button mit der Schrift \"Code\"<br>3. Entweder Klonen Sie das Projekt mit git oder Sie laden das Projekt als .zip Datei herunter und entpacken Sie dieses<br>4. Gehen Sie in den Unterordner SourceCode und öffnen Sie die Datei TvSeriesCalender.sln mit Visual Studio<br>5. Kompilieren Sie das projekt und starten Sie die kompilierte .exe-Datei<br>6. Viel spaß mit der Applikation!<br>",
    },
};